import { Inter } from "next/font/google";
import Header from "./header/page";
import Nav from "./nav/page";
import Footer from "./footer/page";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "한국ICT 인재 개발원",
  description: "Generated by create next app",
  icons :{
    icon : '/images/ict_favicon.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
         <Header />
         <Nav /> 
          {children}
         <Footer />
      </body>
    </html>
  );
}